### ISSUE TITLE
Question: Compute and software requirements

### ISSUE THREAD

**Issue by raunakbh92** [dadecampo/SafeRLAUV#1]
Thank you for sharing your source code. I have a few questions:

1. What version of Unity is required?
2. What version of Zibra is required and how should I go about getting access to it?
3. What are the minimum server and GPU requirements?

If you have any further guidelines/detailed installation instructions, will be very grateful if you could share those.

Thank you

**Comment by dadecampo** [comment]
Hi @raunakbh92.
The project was developed using **Unity 2023.2.15f1**.
The required Zibra Liquid package version is v2.1.5 and can be downloaded through the Unity Assets Store, you can purchase it at this link: https://assetstore.unity.com/packages/tools/physics/zibra-liquid-266451.
As far as the minimum requirements are concerned, it depends very much on how well you want to simulate the water physics through Zibra AI, the settings you find within the project run smoothly on a RTX 3080, but you can adjust them to run simulations on less powerful hardware.

**Comment by sadadsads** [comment]
when i git clone this project, it will print
"batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/dadecampo/SafeRLAUV.git/info/lfs'"
do you know how to solve this problem?

**Comment by dadecampo** [comment]
> when i git clone this project, it will print "batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. Failed to fetch some objects from 'https://github.com/dadecampo/SafeRLAUV.git/info/lfs'" do you know how to solve this problem?

Solved with the last commit.
