### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by MPHarryZhang** [dadecampo/SafeRLAUV#2]
Excuse me. Could you tell us how to run this project? When we ran it, we received the error that "TypeError: Invalid first argument to `register()`. typing.Dict[mlagents.trainers.settings.RewardSignalType, mlagents.trainers.settings.RewardSignalSettings] is not a class.". We don't know how to deal with it. Thank you very much.

**Comment by dadecampo** [comment]
Hi Harry!
Which version of python are you using?

**Comment by MPHarryZhang** [comment]
> Hi Harry! Which version of python are you using?

(aquatic_navigation) C:\Users\Harry>python --version
Python 3.10.12

**Comment by dadecampo** [comment]
> > Hi Harry! Which version of python are you using?
> 
> (aquatic_navigation) C:\Users\Harry>python --version Python 3.10.12

And which version of mlagents / pytorch?

**Comment by MPHarryZhang** [comment]
> > > Hi Harry! Which version of python are you using?
> > 
> > 
> > (aquatic_navigation) C:\Users\Harry>python --version Python 3.10.12
> 
> And which version of mlagents / pytorch?

pytorch: 2.2.2+cpu; mlagents: 0.28.0

**Comment by MPHarryZhang** [comment]
> > > Hi Harry! Which version of python are you using?
> > 
> > 
> > (aquatic_navigation) C:\Users\Harry>python --version Python 3.10.12
> 
> And which version of mlagents / pytorch?

Do we need to download any additional software? (Not included in the requirement. txt)

**Comment by dadecampo** [comment]
> > > > Hi Harry! Which version of python are you using?
> > > 
> > > 
> > > (aquatic_navigation) C:\Users\Harry>python --version Python 3.10.12
> > 
> > And which version of mlagents / pytorch?
> 
> Do we need to download any additional software? (Not included in the requirement. txt)

Try to pull and run again the requirements.txt, i made a fix.
The correct mlagents version should be the 1.1.0.dev

**Comment by MPHarryZhang** [comment]
> > > > > Hi Harry! Which version of python are you using?
> > > > 
> > > > 
> > > > (aquatic_navigation) C:\Users\Harry>python --version Python 3.10.12
> > > 
> > > 
> > > And which version of mlagents / pytorch?
> > 
> > 
> > Do we need to download any additional software? (Not included in the requirement. txt)
> 
> Try to pull and run again the requirements.txt, i made a fix. The correct mlagents version should be the 1.1.0.dev

Thank you very much. We have achieved to get the unity 3D's window. We will continue to learn using this platform.
