### ISSUE TITLE
Loading scenes error in Unity

### ISSUE THREAD

**Issue by zbwby819** [dadecampo/SafeRLAUV#3]
Hi, thank you for sharing the project. 

But I have some trouble in loading the Scenes in Unity it shows some errors like these: The GUID inside 'Assets/Scenes/Other/WaterBakedState 1.bytes.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.

Assertion failed on expression: 'IsMapping()'

Assets\Scripts\RoverMovement\BouyancyObject.cs(56,16): error CS1061: 'Rigidbody' does not contain a definition for 'linearDamping' and no accessible extension method 'linearDamping' accepting a first argument of type 'Rigidbody' could be found (are you missing a using directive or an assembly reference?)

Do you know how to fix these and re-edit your scenes in Unity? 
(I install the same version of Unity and Zibra)

Thanks

**Comment by dadecampo** [comment]
Hi zbwby819,
This could be a problem with Git LFS.
I have made changes that reduce the size of some 3d models so that I no longer need to use Git LFS.
I would ask you to clone the repository again in order to check if these problems are still present.
Thank you very much!

**Comment by zbwby819** [comment]
Thanks, dadecampo 

The scenes can now be loaded correctly! Much appreciated!
